#!/bin/bash
cd /media/wamoje/Clip\ Sport/Music
WRKFIL=$(mktemp)
find . -maxdepth 1 -type f -iname "*.mp3" >$WRKFIL
while read TRACK
do
  TARGET=$(du -s D* | grep 'D[0-9]$' | sort -n | head -n 1 | cut -f2)
  mv "$TRACK" $TARGET
  echo $TARGET now contains $TRACK
done <$WRKFIL
