#!/bin/bash
#  Zoek 1 tot 3 argumenten in textfiles in MP3/Index en in mp3 bestandsnamen in MP3
_INDEXDIR=/home/wamoje/Dropbox/Public/Index
_MP3DIR=/media/wamoje/MyDrive/MP3
case $# in 
 1) echo "Index:"
   grep -i "$1" $_INDEXDIR/*.txt
   echo "MP3:"
   ls -R $_MP3DIR | grep -i "$1"
   ;;
 2) echo "Index:"
   grep -i "$1" $_INDEXDIR/*.txt | grep -i "$2"
   echo "MP3:"
   ls -R $_MP3DIR | grep -i "$1" | grep -i "$2"
   ;;
 3) echo "Index:"
   grep -i "$1" $_INDEXDIR/*.txt | grep -i "$2" | grep -i "$3"
   echo "MP3:"
   ls -R $_MP3DIR | grep -i "$1" | grep -i "$2" | grep -i "$3"
   ;;
 4) echo "Index:"
   grep -i "$1" $_INDEXDIR/*.txt | grep -i "$2" | grep -i "$3" | grep -i "$4"
   echo "MP3:"
   ls -R $_MP3DIR | grep -i "$1" | grep -i "$2" | grep -i "$3" | grep -i "$4"
   ;;
 *) echo "1 tot 4 variabelen mee geven" 
   exit 1 ;;
esac
